extends Resource
class_name Stats

enum MOD_MODE {
	SET,
	ADD,
	MULTIPLY,
	INCREASE_PERCENT,
	DECREASE_PERCENT
}

enum ATTRIBUTES {
	# Player
  PLAYER_SPEED_MULTIPLIER,
  RATE_OF_FIRE_MULTIPLIER,
  PROJECTILE_SPEED_MULTIPLIER,
	MAX_HEALTH, # idk how this one is going to work
	
	# Enemy
	ENEMY_RATE_OF_FIRE_MULTIPLIER,
	ENEMY_MOVEMENT_SPEED_MULTIPLIER,
  ENEMY_PROJECTILE_SPEED_MULTIPLIER,
}

const starting_values = {
	ATTRIBUTES.PLAYER_SPEED_MULTIPLIER: 1,
	ATTRIBUTES.RATE_OF_FIRE_MULTIPLIER: 1,
	ATTRIBUTES.PROJECTILE_SPEED_MULTIPLIER: 1,
	ATTRIBUTES.MAX_HEALTH: 2,
	ATTRIBUTES.ENEMY_RATE_OF_FIRE_MULTIPLIER: 1,
	ATTRIBUTES.ENEMY_MOVEMENT_SPEED_MULTIPLIER: 1,
	ATTRIBUTES.ENEMY_PROJECTILE_SPEED_MULTIPLIER: 1,
}

const attribute_names = {
	ATTRIBUTES.PLAYER_SPEED_MULTIPLIER: "Move Speed",
	ATTRIBUTES.RATE_OF_FIRE_MULTIPLIER: "Rate of Fire",
	ATTRIBUTES.PROJECTILE_SPEED_MULTIPLIER: "Projectile Speed",
	ATTRIBUTES.MAX_HEALTH: "Max Health",
	ATTRIBUTES.ENEMY_RATE_OF_FIRE_MULTIPLIER: "Enemy Rate of Fire",
	ATTRIBUTES.ENEMY_MOVEMENT_SPEED_MULTIPLIER: "Enemy Movement Speed",
	ATTRIBUTES.ENEMY_PROJECTILE_SPEED_MULTIPLIER: "Enemy Projectile Speed"
}