extends Resource
class_name Stats

enum MOD_MODE {
	SET,
	ADD,
	MULTIPLY,
	INCREASE_PERCENT,
	DECREASE_PERCENT
}

enum ATTRIBUTES {
  PLAYER_SPEED_MULTIPLIER,
  RATE_OF_FIRE_MULTIPLIER,
	ENEMY_RATE_OF_FIRE_MULTIPLIER
}

const starting_values = {
	ATTRIBUTES.PLAYER_SPEED_MULTIPLIER: 1,
	ATTRIBUTES.RATE_OF_FIRE_MULTIPLIER: 1,
	ATTRIBUTES.ENEMY_RATE_OF_FIRE_MULTIPLIER: 1
}

const attribute_names = {
	ATTRIBUTES.PLAYER_SPEED_MULTIPLIER: "Move Speed",
	ATTRIBUTES.RATE_OF_FIRE_MULTIPLIER: "Rate of Fire",
	ATTRIBUTES.RATE_OF_FIRE_MULTIPLIER: "Enemy Rate of Fire"
}